blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('article/<int:permalink_id>/', views.article, name='article'),
]

console/urls.py
from django.urls import path
from . import views

app_name = 'console'
urlpatterns = [
    path('update/', views.update, name='update'),
    path('edit/<int:permalink_id>/', views.edit, name='edit'),
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('console/', include('console.urls', namespace='console')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from pelican.contents import Article as _Article
import core


# Create your views here.
def article(request, permalink_id):
    for article in core.pelican.articles:
        if permalink_id == int(article.metadata['permalink']):
            return render(request, 'blog/article.html', {
                'article': article
            })
    return redirect('console:index')

console/views.py
import os
from django.shortcuts import render, redirect, reverse, HttpResponse
import core
import settings


# Create your views here.

def index(request):
    core.pelican.read(True)
    articles = core.pelican.articles
    headers = [item[0] for item in settings.get_fields(articles[0])]
    articles.sort(key=lambda article: -int(article.metadata['permalink']))
    articles = [settings.get_fields(article) for article in articles]
    articles = [[value for key, value in article] for article in articles]
    return render(request, 'console/index.html', {
        'headers': headers,
        'articles': articles,
    })


def update(request):
    core.pelican.read(local=True)
    return HttpResponse(True)


def edit(request, permalink_id):
    path = core.pelican.get_article(permalink_id).source_path
    os.popen(f'"{settings.EDITOR_PATH}" "{path}"')
    return redirect('blog:article', permalink_id=permalink_id)

templates/base.html
{% load static %}
{% load active_link_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}无标题页{% endblock %} | Pelican博客管理器</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css">
    {% block head %}
    {% endblock %}
</head>
<body class="col-xs-12">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'console:index' %}">Pelican博客管理器</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link {% active_link 'console:index' %}" href="{% url 'console:index' %}">首页</a>
        </li>
    </ul>
</nav>

<div class="row">
    <div class="list-group col-2 p-3 pl-4 text-center">

        <script>
            async function updatePage() {
                await fetch('{% url "console:update" %}');
                location.reload();
            }
        </script>
        <a class="list-group-item list-group-item-action" href="javascript: updatePage()">更新博客</a>
        {% block sidebar %}
        {% endblock %}
    </div>

    <div class="col-10 body p-3 pr-4">
        {% block body %}
        {% endblock %}
    </div>

</div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js"></script>
</html>

templates/blog/article.html
{% extends 'base.html' %}
{% load static %}

{% block title %}博文{{ article.metadata.permalink }}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'blog/article.css' %}">
{% endblock %}

{% block sidebar %}
    <a class="list-group-item list-group-item-action" href="{% url 'console:edit' article.metadata.permalink %}">编辑</a>
{% endblock %}

{% block body %}
    <h1 class="title text-center my-5">{{ article.title }}</h1>
    {{ article.content |safe }}
{% endblock %}

templates/console/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}无标题页{% endblock %} | Pelican博客管理器</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css">
    {% block head %}
    {% endblock %}
</head>
<body class="col-xs-12">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'console:index' %}">Pelican博客管理器</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'console:index' %}">首页</a>
        </li>
    </ul>
</nav>

<div class="body">
    {% block body %}
    {% endblock %}
</div>


</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js"></script>
</html>

templates/console/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}首页{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'console/index.css' %}">
{% endblock %}

{% block body %}
    <table class="table text-center">
        <thead>
        <tr>
            {% for header in headers %}
                <th>{{ header }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr onclick="location.href='{% url 'blog:article' article.0 %}'">
                {% for cell in article %}
                    <td>{{ cell }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}